version: '2'
services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always

    nimbus:
        image: storm:1.0.3
        container_name: nimbus
        command: storm nimbus
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 6627:6627

    supervisor:
        image: storm:1.0.3
        container_name: supervisor
        command: storm supervisor
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
            - zookeeper
        restart: always

    ui:
        image: storm:1.0.3
        container_name: ui
        command: storm ui
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
        restart: always
        ports:
            - 8080:8080

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        depends_on:
            - zookeeper
        restart: always 
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
            KAFKA_CREATE_TOPICS: "twitter-topic:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_MESSAGE_MAX_BYTES: 2000000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

